-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."ambassador supplier"
(
    id integer NOT NULL,
    social_credit integer NOT NULL,
    name character varying(30) NOT NULL,
    order_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."order"
(
    id integer NOT NULL,
    wedding date NOT NULL,
    number_of_guests integer NOT NULL,
    payment integer NOT NULL,
    location character varying(100) NOT NULL,
    services character varying(20) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."detail service"
(
    id integer NOT NULL,
    musicians character varying(3) NOT NULL,
    "video recording" character varying(3) NOT NULL,
    toastmaster character varying(3) NOT NULL,
    choreographer character varying(3) NOT NULL,
    chef character varying(3) NOT NULL,
    services_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.grooms
(
    id integer NOT NULL,
    name character varying NOT NULL,
    age integer NOT NULL,
    ambassador_id integer NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public."ambassador supplier"
    ADD FOREIGN KEY (order_id)
    REFERENCES public."order" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."detail service"
    ADD FOREIGN KEY (services_id)
    REFERENCES public."order" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.grooms
    ADD FOREIGN KEY (ambassador_id)
    REFERENCES public."ambassador supplier" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;